/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/models/6490f6229837221882d60895-2.glb
*/

import { useEffect, useRef } from "react";
import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

export function Avatar(props) {
    const { animation, poseOnly = false, poseTime = 0 } = props;
    const headFollow = false;
    const cusorFollow = false;
  const group = useRef();
  const activeActionRef = useRef(null);
  const { nodes, materials } = useGLTF("models/6490f6229837221882d60895-2.glb");



  const { animations: typeingAnimation } = useFBX("animations/Typing.fbx");
  const { animations: fallingAnimation } = useFBX("animations/Falling.fbx");
  const { animations: standingAnimation } = useFBX("animations/Standing.fbx");
  const { animations: fallingIdleAnimation } = useFBX("animations/Falling_Idle.fbx");
  const { animations: fallingLandingAnimation } = useFBX("animations/Falling_Landing.fbx");
  const { animations: waveAnimation } = useFBX("animations/Wave.fbx");
  const { animations: pointingAnimation } = useFBX("animations/Pointing.fbx");



  typeingAnimation[0].name = "Typing";
  fallingAnimation[0].name = "Falling";
  standingAnimation[0].name = "Standing";
  fallingIdleAnimation[0].name = "Falling_Idle";
  fallingLandingAnimation[0].name = "Falling_Landing";
  waveAnimation[0].name = "Wave";
  pointingAnimation[0].name = "Pointing";

  const { actions } = useAnimations([typeingAnimation[0],standingAnimation[0],fallingAnimation[0],fallingIdleAnimation[0],fallingLandingAnimation[0],waveAnimation[0],pointingAnimation[0]],group);


  useFrame((state)=>{
    if(headFollow) group.current.getObjectByName("Head").lookAt(state.camera.position);
    if(cusorFollow) {
        group.current.getObjectByName("Head").lookAt(state.camera.position);
        const target = new THREE.Vector3(state.mouse.x,state.mouse.y,1);
        group.current.getObjectByName("Spine").lookAt(target);
    }
  });

  useEffect(() => {
    const coolTint = new THREE.Color("#2d8b92");
    const warmTint = new THREE.Color("#d29a74");

    function blendMaterial(name, coolMix = 0.08, warmMix = 0.02) {
      const material = materials?.[name];

      if (!material || !material.color) {
        return;
      }

      material.color.lerp(coolTint, coolMix);
      material.color.lerp(warmTint, warmMix);

      if ("roughness" in material) {
        material.roughness = Math.min(1, material.roughness * 1.08);
      }

      if ("metalness" in material) {
        material.metalness = Math.max(0, material.metalness * 0.82);
      }

      if ("envMapIntensity" in material) {
        material.envMapIntensity = 0.3;
      }

      material.needsUpdate = true;
    }

    blendMaterial("Wolf3D_Body", 0.1, 0.03);
    blendMaterial("Wolf3D_Outfit_Top", 0.11, 0.03);
    blendMaterial("Wolf3D_Outfit_Bottom", 0.06, 0.02);
    blendMaterial("Wolf3D_Outfit_Footwear", 0.04, 0.02);
    blendMaterial("Wolf3D_Hair", 0.05, 0.01);
    blendMaterial("Wolf3D_Skin", 0.04, 0.01);
    blendMaterial("Wolf3D_Eye", 0.04, 0.01);
    blendMaterial("Wolf3D_Teeth", 0.02, 0);

    const glassesMaterial = materials?.Wolf3D_Glasses;

    if (!glassesMaterial) {
      return;
    }

    glassesMaterial.side = THREE.DoubleSide;
    glassesMaterial.depthWrite = true;
    glassesMaterial.depthTest = true;
    glassesMaterial.transparent = true;
    glassesMaterial.envMapIntensity = 0.2;
    glassesMaterial.color.lerp(coolTint, 0.08);
    glassesMaterial.color.lerp(warmTint, 0.02);
    glassesMaterial.needsUpdate = true;
  }, [materials]);

  useEffect(()=>{
    if (!animation || !actions?.[animation]) {
      return undefined;
    }

    const nextAction = actions[animation];
    const currentAction = activeActionRef.current;
    const sameAction = currentAction === nextAction;
    const clipDuration = nextAction.getClip()?.duration || 0;
    const clampedPoseTime =
      clipDuration > 0
        ? THREE.MathUtils.clamp(poseTime, 0, Math.max(clipDuration - 0.001, 0))
        : 0;

    if (!sameAction) {
      if (currentAction) {
        currentAction.fadeOut(0.32);
      }

      nextAction.reset().fadeIn(0.32).play();
      activeActionRef.current = nextAction;
    } else if (!nextAction.isRunning()) {
      nextAction.play();
    }

    if (poseOnly) {
      nextAction.paused = false;
      nextAction.time = clampedPoseTime;
      nextAction.paused = true;
    } else {
      nextAction.paused = false;
    }

    return undefined;
  }, [actions, animation, poseOnly, poseTime]);

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh frustumCulled={false} geometry={nodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Wolf3D_Body.skeleton} />
      <skinnedMesh frustumCulled={false} geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
      <skinnedMesh frustumCulled={false} geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
      <skinnedMesh frustumCulled={false} geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
      <skinnedMesh frustumCulled={false} geometry={nodes.Wolf3D_Hair.geometry} material={materials.Wolf3D_Hair} skeleton={nodes.Wolf3D_Hair.skeleton} />
      <skinnedMesh
        frustumCulled={false}
        renderOrder={12}
        geometry={nodes.Wolf3D_Glasses.geometry}
        material={materials.Wolf3D_Glasses}
        skeleton={nodes.Wolf3D_Glasses.skeleton}
      />
      <skinnedMesh frustumCulled={false} name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeLeft.skeleton} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
      <skinnedMesh frustumCulled={false} name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeRight.skeleton} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
      <skinnedMesh frustumCulled={false} name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Wolf3D_Head.skeleton} morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences} />
      <skinnedMesh frustumCulled={false} name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Wolf3D_Teeth.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences} />
    </group>
  );
}

useGLTF.preload("models/6490f6229837221882d60895-2.glb");
