/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 Desk.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Desk(props) {
  const { nodes, materials } = useGLTF('models/Desk-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-1.32, 5.77, -5.78]} rotation={[-Math.PI / 2, 0, 0]} scale={2.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Keys1} />
          <mesh geometry={nodes.defaultMaterial001.geometry} material={materials.Body1} />
        </group>
      </group>
      <group position={[1.32, 5.67, -4.26]} scale={14.84}>
        <group position={[0, 0.01, -0.01]} rotation={[Math.PI / 2, 0, 0]} scale={0.02}>
          <mesh geometry={nodes.MouseThermaltakeBlack015_1.geometry} material={materials['Material.134']} />
          <mesh geometry={nodes.MouseThermaltakeBlack015_2.geometry} material={materials['Material.126']} />
          <mesh geometry={nodes.MouseThermaltakeBlack015_3.geometry} material={materials['Material.125']} />
          <mesh geometry={nodes.MouseThermaltakeBlack015_4.geometry} material={materials['Material.028']} />
          <mesh geometry={nodes.MouseThermaltakeBlack015_5.geometry} material={materials['Material.125']} />
          <mesh geometry={nodes.MouseThermaltakeBlack015_6.geometry} material={materials['Material.126']} />
          <mesh geometry={nodes.MouseThermaltakeBlack015_7.geometry} material={materials['Material.127']} />
          <mesh geometry={nodes.MouseThermaltakeBlack015_8.geometry} material={materials['main body.001']} />
          <mesh geometry={nodes.MouseThermaltakeBlack015_9.geometry} material={materials['Material.132']} />
          <mesh geometry={nodes.MouseThermaltakeBlack015_10.geometry} material={materials['Material.122']} />
          <mesh geometry={nodes.MouseThermaltakeBlack015_11.geometry} material={materials['Material.124']} />
          <mesh geometry={nodes.MouseThermaltakeBlack015_12.geometry} material={materials['Material.123']} />
          <mesh geometry={nodes.MouseThermaltakeBlack015_13.geometry} material={materials['Material.124']} />
          <mesh geometry={nodes.MouseThermaltakeBlack015_14.geometry} material={materials['Material.128']} />
        </group>
      </group>
      <group position={[-1.3, 11.54, -7.46]} scale={[0.44, 0.39, 0.44]}>
        <mesh geometry={nodes.Cube155_1.geometry} material={materials.RenderMonitor} />
        <mesh geometry={nodes.Cube155_2.geometry} material={materials.Case} />
        <mesh geometry={nodes.Cube155_3.geometry} material={materials.USB} />
      </group>
      {/* <group position={[-1.27, 5.66, -5.15]} rotation={[Math.PI, -1.56, Math.PI]} scale={[1.95, 14.66, 4.49]}>
        <mesh geometry={nodes.Plane006_1.geometry} material={materials['Material.121']} />
        <mesh geometry={nodes.Plane006_2.geometry} material={materials['Material.120']} />
      </group> */}
      <group position={[0, -0.02, -5.3]} rotation={[Math.PI / 2, 0, 0]} scale={[3.81, 2.02, 2.02]}>
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_1'].geometry} material={materials['Material.021']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_2'].geometry} material={materials['1042']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_3'].geometry} material={materials['1042']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_4'].geometry} material={materials['1045']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_5'].geometry} material={materials['Material.003']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_6'].geometry} material={materials['Material.004']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_7'].geometry} material={materials['Material.005']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_8'].geometry} material={materials['Material.006']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_9'].geometry} material={materials['Material.027']} />
        <mesh geometry={nodes['Escritorio-pc-Teclado-Pantalla-mouse_10'].geometry} material={materials['Material.028']} />
      </group>
      <mesh geometry={nodes.BezierCurve.geometry} material={materials['Material.021']} position={[7.47, 9.35, -6.87]} rotation={[Math.PI, 1.08, -Math.PI / 2]} scale={0.15} />
      <mesh geometry={nodes.BezierCurve040.geometry} material={materials['Material.021']} position={[8.09, 6.47, -5.89]} rotation={[-Math.PI, 1.08, 2.15]} scale={0.35} />
      <mesh geometry={nodes.BezierCurve001.geometry} material={materials['Material.021']} position={[7.47, 9.35, -6.87]} rotation={[Math.PI, 1.08, -Math.PI / 2]} scale={0.15} />
      <mesh geometry={nodes.BezierCurve041.geometry} material={materials['Material.021']} position={[8.09, 6.47, -5.9]} rotation={[-Math.PI, 1.08, 2.15]} scale={0.35} />
      <mesh geometry={nodes.BezierCurve002.geometry} material={materials['Material.021']} position={[7.46, 9.35, -6.88]} rotation={[Math.PI, 1.08, -Math.PI / 2]} scale={0.15} />
      <mesh geometry={nodes.BezierCurve042.geometry} material={materials['Material.021']} position={[8.1, 6.47, -5.87]} rotation={[-Math.PI, 1.08, 2.15]} scale={0.35} />
      <mesh geometry={nodes.BezierCurve003.geometry} material={materials['Material.021']} position={[7.46, 9.35, -6.89]} rotation={[Math.PI, 1.08, -Math.PI / 2]} scale={0.15} />
      <mesh geometry={nodes.BezierCurve043.geometry} material={materials['Material.021']} position={[8.11, 6.47, -5.85]} rotation={[-Math.PI, 1.08, 2.15]} scale={0.35} />
      <mesh geometry={nodes.BezierCurve004.geometry} material={materials['Material.021']} position={[7.49, 9.35, -6.83]} rotation={[Math.PI, 1.08, -Math.PI / 2]} scale={0.15} />
      <mesh geometry={nodes.BezierCurve044.geometry} material={materials['Material.021']} position={[7.43, 6.47, -7.14]} rotation={[-Math.PI, 1.08, 2.15]} scale={0.35} />
      <mesh geometry={nodes.BezierCurve005.geometry} material={materials['Material.021']} position={[7.49, 9.35, -6.84]} rotation={[Math.PI, 1.08, -Math.PI / 2]} scale={0.15} />
      <mesh geometry={nodes.BezierCurve045.geometry} material={materials['Material.021']} position={[7.43, 6.47, -7.15]} rotation={[-Math.PI, 1.08, 2.15]} scale={0.35} />
      <mesh geometry={nodes.BezierCurve006.geometry} material={materials['Material.021']} position={[7.48, 9.35, -6.84]} rotation={[Math.PI, 1.08, -Math.PI / 2]} scale={0.15} />
      <mesh geometry={nodes.BezierCurve046.geometry} material={materials['Material.021']} position={[7.44, 6.47, -7.13]} rotation={[-Math.PI, 1.08, 2.15]} scale={0.35} />
      <mesh geometry={nodes.BezierCurve007.geometry} material={materials['Material.021']} position={[7.48, 9.35, -6.85]} rotation={[Math.PI, 1.08, -Math.PI / 2]} scale={0.15} />
      <mesh geometry={nodes.BezierCurve047.geometry} material={materials['Material.021']} position={[7.44, 6.47, -7.12]} rotation={[-Math.PI, 1.08, 2.15]} scale={0.35} />
      <mesh geometry={nodes.BezierCurve008.geometry} material={materials['Material.021']} position={[7.47, 9.32, -6.87]} rotation={[Math.PI, 1.08, -Math.PI / 2]} scale={0.15} />
      <mesh geometry={nodes.BezierCurve009.geometry} material={materials['Material.021']} position={[7.46, 9.32, -6.88]} rotation={[Math.PI, 1.08, -Math.PI / 2]} scale={0.15} />
      <mesh geometry={nodes.BezierCurve010.geometry} material={materials['Material.021']} position={[7.46, 9.32, -6.89]} rotation={[Math.PI, 1.08, -Math.PI / 2]} scale={0.15} />
      <mesh geometry={nodes.BezierCurve011.geometry} material={materials['Material.021']} position={[7.46, 9.32, -6.89]} rotation={[Math.PI, 1.08, -Math.PI / 2]} scale={0.15} />
      <mesh geometry={nodes.BezierCurve012.geometry} material={materials['Material.021']} position={[7.49, 9.32, -6.83]} rotation={[Math.PI, 1.08, -Math.PI / 2]} scale={0.15} />
      <mesh geometry={nodes.BezierCurve013.geometry} material={materials['Material.021']} position={[7.48, 9.32, -6.84]} rotation={[Math.PI, 1.08, -Math.PI / 2]} scale={0.15} />
      <mesh geometry={nodes.BezierCurve014.geometry} material={materials['Material.021']} position={[7.48, 9.32, -6.85]} rotation={[Math.PI, 1.08, -Math.PI / 2]} scale={0.15} />
      <mesh geometry={nodes.BezierCurve015.geometry} material={materials['Material.021']} position={[7.47, 9.32, -6.86]} rotation={[Math.PI, 1.08, -Math.PI / 2]} scale={0.15} />
      <mesh geometry={nodes.BezierCurve016.geometry} material={materials['Material.021']} position={[8.25, 8.32, -5.67]} rotation={[0, 0.49, 0]} scale={0.51} />
      <mesh geometry={nodes.BezierCurve017.geometry} material={materials['Material.021']} position={[8.27, 8.32, -5.63]} rotation={[0, 0.49, 0]} scale={0.51} />
      <mesh geometry={nodes.BezierCurve018.geometry} material={materials['Material.021']} position={[8.25, 8.28, -5.67]} rotation={[0, 0.49, 0]} scale={0.51} />
      <mesh geometry={nodes.BezierCurve019.geometry} material={materials['Material.021']} position={[8.27, 8.28, -5.63]} rotation={[0, 0.49, 0]} scale={0.51} />
      <mesh geometry={nodes.BezierCurve020.geometry} material={materials['Material.021']} position={[8.25, 8.38, -5.67]} rotation={[0, 0.49, 0]} scale={0.51} />
      <mesh geometry={nodes.BezierCurve021.geometry} material={materials['Material.021']} position={[8.27, 8.38, -5.63]} rotation={[0, 0.49, 0]} scale={0.51} />
      <mesh geometry={nodes.BezierCurve022.geometry} material={materials['Material.021']} position={[8.25, 8.35, -5.67]} rotation={[0, 0.49, 0]} scale={0.51} />
      <mesh geometry={nodes.BezierCurve023.geometry} material={materials['Material.021']} position={[8.27, 8.35, -5.63]} rotation={[0, 0.49, 0]} scale={0.51} />
      <mesh geometry={nodes.BezierCurve024.geometry} material={materials['Material.021']} position={[8.25, 8.45, -5.67]} rotation={[0, 0.49, 0]} scale={0.51} />
      <mesh geometry={nodes.BezierCurve025.geometry} material={materials['Material.021']} position={[8.27, 8.45, -5.63]} rotation={[0, 0.49, 0]} scale={0.51} />
      <mesh geometry={nodes.BezierCurve026.geometry} material={materials['Material.021']} position={[8.25, 8.41, -5.67]} rotation={[0, 0.49, 0]} scale={0.51} />
      <mesh geometry={nodes.BezierCurve027.geometry} material={materials['Material.021']} position={[8.27, 8.41, -5.63]} rotation={[0, 0.49, 0]} scale={0.51} />
      <mesh geometry={nodes.BezierCurve028.geometry} material={materials['Material.021']} position={[8.25, 8.51, -5.67]} rotation={[0, 0.49, 0]} scale={0.51} />
      <mesh geometry={nodes.BezierCurve029.geometry} material={materials['Material.021']} position={[8.27, 8.51, -5.63]} rotation={[0, 0.49, 0]} scale={0.51} />
      <mesh geometry={nodes.BezierCurve030.geometry} material={materials['Material.021']} position={[8.25, 8.48, -5.67]} rotation={[0, 0.49, 0]} scale={0.51} />
      <mesh geometry={nodes.BezierCurve031.geometry} material={materials['Material.021']} position={[8.27, 8.48, -5.63]} rotation={[0, 0.49, 0]} scale={0.51} />
      <mesh geometry={nodes.BezierCurve032.geometry} material={materials['Material.021']} position={[8.25, 8.57, -5.67]} rotation={[0, 0.49, 0]} scale={0.51} />
      <mesh geometry={nodes.BezierCurve033.geometry} material={materials['Material.021']} position={[8.27, 8.57, -5.63]} rotation={[0, 0.49, 0]} scale={0.51} />
      <mesh geometry={nodes.BezierCurve035.geometry} material={materials['Material.021']} position={[8.27, 8.54, -5.63]} rotation={[0, 0.49, 0]} scale={0.51} />
      <mesh geometry={nodes.BezierCurve034.geometry} material={materials['Material.021']} position={[8.25, 8.54, -5.67]} rotation={[0, 0.49, 0]} scale={0.51} />
      <mesh geometry={nodes.BezierCurve036.geometry} material={materials['Material.021']} position={[8.25, 8.25, -5.67]} rotation={[0, 0.49, 0]} scale={0.51} />
      <mesh geometry={nodes.BezierCurve037.geometry} material={materials['Material.021']} position={[8.27, 8.25, -5.63]} rotation={[0, 0.49, 0]} scale={0.51} />
      <mesh geometry={nodes.BezierCurve038.geometry} material={materials['Material.021']} position={[8.25, 8.22, -5.67]} rotation={[0, 0.49, 0]} scale={0.51} />
      <mesh geometry={nodes.BezierCurve039.geometry} material={materials['Material.021']} position={[8.27, 8.22, -5.63]} rotation={[0, 0.49, 0]} scale={0.51} />
      <mesh geometry={nodes.BezierCurve048.geometry} material={materials['Material.065']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.47, Math.PI]} scale={[0.21, 0.21, 0.18]} />
      <mesh geometry={nodes.BezierCurve049.geometry} material={materials['Material.065']} position={[7.28, 7.59, -6.46]} rotation={[-Math.PI, 0.7, -Math.PI]} scale={[0.21, 0.21, 0.18]} />
      <mesh geometry={nodes.BezierCurve050.geometry} material={materials['Material.065']} position={[7.28, 7.59, -6.46]} rotation={[0, -0.7, 0]} scale={[0.21, 0.21, 0.18]} />
      <mesh geometry={nodes.BezierCurve051.geometry} material={materials['Material.065']} position={[7.28, 7.59, -6.46]} rotation={[Math.PI, 1.47, 0]} scale={[0.21, 0.21, 0.18]} />
      <mesh geometry={nodes.BezierCurve052.geometry} material={materials['Material.021']} position={[7.47, 8.46, -5.94]} rotation={[-1.01, 0.27, 0.41]} scale={0.34} />
      <mesh geometry={nodes.BezierCurve053.geometry} material={materials['Material.021']} position={[7.47, 8.66, -5.94]} rotation={[-1.01, 0.27, 0.41]} scale={0.34} />
      <mesh geometry={nodes.BezierCurve054.geometry} material={materials['Material.021']} position={[8.39, 7.73, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve055.geometry} material={materials['Material.021']} position={[8.39, 7.72, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve056.geometry} material={materials['Material.021']} position={[8.39, 7.71, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve057.geometry} material={materials['Material.021']} position={[8.39, 7.69, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve070.geometry} material={materials['Material.021']} position={[8.39, 7.36, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve071.geometry} material={materials['Material.021']} position={[8.39, 7.34, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve072.geometry} material={materials['Material.021']} position={[8.39, 7.33, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve073.geometry} material={materials['Material.021']} position={[8.39, 7.32, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve058.geometry} material={materials['Material.021']} position={[8.39, 7.63, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve059.geometry} material={materials['Material.021']} position={[8.39, 7.61, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve060.geometry} material={materials['Material.021']} position={[8.39, 7.6, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve061.geometry} material={materials['Material.021']} position={[8.39, 7.59, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve063.geometry} material={materials['Material.021']} position={[8.39, 7.51, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve064.geometry} material={materials['Material.021']} position={[8.39, 7.5, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve067.geometry} material={materials['Material.021']} position={[8.39, 7.46, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve068.geometry} material={materials['Material.021']} position={[8.39, 7.45, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve062.geometry} material={materials['Material.021']} position={[8.39, 7.53, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve065.geometry} material={materials['Material.021']} position={[8.39, 7.49, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve066.geometry} material={materials['Material.021']} position={[8.39, 7.47, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve069.geometry} material={materials['Material.021']} position={[8.39, 7.43, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve074.geometry} material={materials['Material.021']} position={[8.39, 7.22, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve075.geometry} material={materials['Material.021']} position={[8.39, 7.21, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve076.geometry} material={materials['Material.021']} position={[8.39, 7.2, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve077.geometry} material={materials['Material.021']} position={[8.39, 7.18, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve078.geometry} material={materials['Material.021']} position={[8.39, 7.09, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve079.geometry} material={materials['Material.021']} position={[8.39, 7.07, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve080.geometry} material={materials['Material.021']} position={[8.39, 7.06, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve081.geometry} material={materials['Material.021']} position={[8.39, 7.05, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve082.geometry} material={materials['Material.021']} position={[8.39, 6.98, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve083.geometry} material={materials['Material.021']} position={[8.39, 6.97, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve084.geometry} material={materials['Material.021']} position={[8.39, 6.96, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve085.geometry} material={materials['Material.021']} position={[8.39, 6.95, -5.61]} rotation={[-Math.PI, 0.3, 0]} scale={0.12} />
      <mesh geometry={nodes.BezierCurve086.geometry} material={materials['Material.021']} position={[7.27, 6.84, -5.74]} rotation={[-Math.PI, 1.08, Math.PI / 2]} scale={0.85} />
      <mesh geometry={nodes.BezierCurve087.geometry} material={materials['Material.021']} position={[7.27, 6.81, -5.74]} rotation={[-Math.PI, 1.08, Math.PI / 2]} scale={0.85} />
      <mesh geometry={nodes.BezierCurve088.geometry} material={materials['Material.021']} position={[7.29, 6.84, -5.71]} rotation={[-Math.PI, 1.08, Math.PI / 2]} scale={0.85} />
      <mesh geometry={nodes.BezierCurve089.geometry} material={materials['Material.021']} position={[7.29, 6.81, -5.71]} rotation={[-Math.PI, 1.08, Math.PI / 2]} scale={0.85} />
      <mesh geometry={nodes.BezierCurve090.geometry} material={materials['Material.021']} position={[7.3, 6.84, -5.68]} rotation={[-Math.PI, 1.08, Math.PI / 2]} scale={0.85} />
      <mesh geometry={nodes.BezierCurve091.geometry} material={materials['Material.021']} position={[7.3, 6.81, -5.68]} rotation={[-Math.PI, 1.08, Math.PI / 2]} scale={0.85} />
      <mesh geometry={nodes.BezierCurve092.geometry} material={materials['Material.021']} position={[7.31, 6.84, -5.66]} rotation={[-Math.PI, 1.08, Math.PI / 2]} scale={0.85} />
      <mesh geometry={nodes.BezierCurve093.geometry} material={materials['Material.021']} position={[7.31, 6.81, -5.66]} rotation={[-Math.PI, 1.08, Math.PI / 2]} scale={0.85} />
      <mesh geometry={nodes.Circle.geometry} material={materials['Material.093']} position={[7.09, 7.55, -6.87]} rotation={[0, 0.49, 0]} scale={0.34} />
      <mesh geometry={nodes.Circle001.geometry} material={materials['Material.093']} position={[7.46, 7.55, -6.16]} rotation={[0, 0.49, 0]} scale={0.34} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.112']} position={[8.1, 6.08, -4.65]} rotation={[-Math.PI, -0.49, -Math.PI]} scale={[0.76, 0.08, 0.53]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.112']} position={[8.1, 6.37, -4.65]} rotation={[-Math.PI, -0.49, -Math.PI]} scale={[0.76, 0.08, 0.53]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.113']} position={[7.23, 5.8, -6.14]} rotation={[0, 0.49, 0]} scale={0.85} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.116']} position={[7.51, 7.76, -5.55]} rotation={[0, 0.49, 0]} scale={[0.81, -1.99, 1.87]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.021']} position={[7.51, 7.76, -5.55]} rotation={[0, 0.49, 0]} scale={[0.81, -1.99, 1.87]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.114']} position={[7.51, 7.76, -5.55]} rotation={[0, 0.49, 0]} scale={[0.81, -1.99, 1.87]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.113']} position={[7.51, 7.76, -5.55]} rotation={[0, 0.49, 0]} scale={[0.81, -1.99, 1.87]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials['Material.117']} position={[7.76, 8.45, -6.76]} rotation={[0, 0.49, 0]} scale={0.85} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['Material.021']} position={[8.27, 7.6, -5.66]} rotation={[0, 0.49, 0]} scale={[0.03, 0.04, 0.03]} />
      <mesh geometry={nodes.Cube047.geometry} material={materials['Material.021']} position={[8.22, 8.39, -5.71]} rotation={[0, 0.49, 0]} scale={[0.03, -0.21, 0.03]} />
      <mesh geometry={nodes.Cube048.geometry} material={materials['Material.021']} position={[7.5, 9.23, -6.88]} rotation={[0, 0.49, 0]} scale={[0.03, 0.03, 0.07]} />
      <mesh geometry={nodes.Cube090.geometry} material={materials['Material.021']} position={[8.21, 6.74, -5.72]} rotation={[0, 0.49, 0]} scale={[-0.02, -0.02, -0.05]} />
      <mesh geometry={nodes.Cube092.geometry} material={materials['Material.021']} position={[8.96, 9.72, -4.6]} rotation={[0, 0.49, 0]} scale={0.06} />
      <mesh geometry={nodes.Cube093.geometry} material={materials['Material.021']} position={[8.87, 9.7, -4.75]} rotation={[0, 0.49, 0]} scale={[0.06, 0.06, 0.01]} />
      <mesh geometry={nodes.Cube146.geometry} material={materials['Material.021']} position={[8.27, 7.71, -5.66]} rotation={[0, 0.49, 0]} scale={[0.03, 0.04, 0.03]} />
      <mesh geometry={nodes.Cube147.geometry} material={materials['Material.021']} position={[8.27, 7.48, -5.66]} rotation={[0, 0.49, 0]} scale={[0.03, 0.06, 0.03]} />
      <mesh geometry={nodes.Cube148.geometry} material={materials['Material.021']} position={[8.27, 7.33, -5.66]} rotation={[0, 0.49, 0]} scale={[0.03, 0.06, 0.03]} />
      <mesh geometry={nodes.Cube149.geometry} material={materials['Material.021']} position={[8.27, 7.19, -5.66]} rotation={[0, 0.49, 0]} scale={[0.03, 0.06, 0.03]} />
      <mesh geometry={nodes.Cube150.geometry} material={materials['Material.021']} position={[8.27, 7.07, -5.66]} rotation={[0, 0.49, 0]} scale={0.03} />
      <mesh geometry={nodes.Cube151.geometry} material={materials['Material.021']} position={[8.27, 6.97, -5.66]} rotation={[0, 0.49, 0]} scale={0.03} />
      <mesh geometry={nodes.Cube152.geometry} material={materials['Material.021']} position={[8.81, 9.7, -4.87]} rotation={[0, 0.49, 0]} scale={[0.06, 0.06, 0.01]} />
      <mesh geometry={nodes.Cube153.geometry} material={materials['Material.060']} position={[8.75, 9.7, -4.99]} rotation={[0, 0.49, 0]} scale={[0.06, 0.06, 0.01]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Material.110']} position={[7.76, 8.45, -6.76]} rotation={[0, 0.49, 0]} scale={0.85} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.107']} position={[7.76, 8.45, -6.76]} rotation={[0, 0.49, 0]} scale={0.85} />
      <mesh geometry={nodes.Cube013.geometry} material={materials['Material.106']} position={[7.76, 8.45, -6.76]} rotation={[0, 0.49, 0]} scale={0.85} />
      <mesh geometry={nodes.Cube014.geometry} material={materials['Material.105']} position={[7.76, 8.45, -6.76]} rotation={[0, 0.49, 0]} scale={0.85} />
      <mesh geometry={nodes.Cube015.geometry} material={materials['Material.103']} position={[7.86, 7.73, -6.42]} rotation={[0, 0.49, 0]} scale={0.05} />
      <mesh geometry={nodes.Cube017.geometry} material={materials['Material.103']} position={[7.86, 7.2, -6.42]} rotation={[0, 0.49, 0]} scale={0.05} />
      <mesh geometry={nodes.Cube020.geometry} material={materials['Material.099']} position={[7.86, 6.86, -6.42]} rotation={[0, 0.49, 0]} scale={0.05} />
      <mesh geometry={nodes.Cube016.geometry} material={materials['Material.104']} position={[7.86, 7.73, -6.42]} rotation={[0, 0.49, 0]} scale={0.05} />
      <mesh geometry={nodes.Cube018.geometry} material={materials['Material.104']} position={[7.86, 7.2, -6.42]} rotation={[0, 0.49, 0]} scale={0.05} />
      <mesh geometry={nodes.Cube021.geometry} material={materials['Material.100']} position={[7.86, 6.86, -6.42]} rotation={[0, 0.49, 0]} scale={0.05} />
      <mesh geometry={nodes.Cube019.geometry} material={materials['Material.102']} position={[7.76, 8.45, -6.76]} rotation={[0, 0.49, 0]} scale={0.85} />
      <mesh geometry={nodes.Cube022.geometry} material={materials['Material.101']} position={[7.76, 8.45, -6.76]} rotation={[0, 0.49, 0]} scale={0.85} />
      <mesh geometry={nodes.Cube023.geometry} material={materials['Material.105']} position={[7.76, 8.45, -6.76]} rotation={[0, 0.49, 0]} scale={0.85} />
      <mesh geometry={nodes.Cube024.geometry} material={materials['Material.097']} position={[7.76, 8.45, -6.76]} rotation={[0, 0.49, 0]} scale={0.85} />
      <mesh geometry={nodes.Cube026.geometry} material={materials['Material.097']} position={[7.8, 8.45, -6.69]} rotation={[0, 0.49, 0]} scale={0.85} />
      <mesh geometry={nodes.Cube028.geometry} material={materials['Material.097']} position={[7.84, 8.45, -6.62]} rotation={[0, 0.49, 0]} scale={0.85} />
      <mesh geometry={nodes.Cube030.geometry} material={materials['Material.097']} position={[7.87, 8.45, -6.55]} rotation={[0, 0.49, 0]} scale={0.85} />
      <mesh geometry={nodes.Cube025.geometry} material={materials['Material.117']} position={[7.76, 8.45, -6.76]} rotation={[0, 0.49, 0]} scale={0.85} />
      <mesh geometry={nodes.Cube027.geometry} material={materials['Material.117']} position={[7.8, 8.45, -6.69]} rotation={[0, 0.49, 0]} scale={0.85} />
      <mesh geometry={nodes.Cube029.geometry} material={materials['Material.117']} position={[7.84, 8.45, -6.62]} rotation={[0, 0.49, 0]} scale={0.85} />
      <mesh geometry={nodes.Cube031.geometry} material={materials['Material.117']} position={[7.87, 8.45, -6.55]} rotation={[0, 0.49, 0]} scale={0.85} />
      <mesh geometry={nodes.Cube032.geometry} material={materials['Material.100']} position={[8.07, 9.14, -6.11]} rotation={[0, 0.49, 0]} scale={0.03} />
      <mesh geometry={nodes.Cube033.geometry} material={materials['Material.100']} position={[8.11, 9.14, -6.04]} rotation={[0, 0.49, 0]} scale={0.03} />
      <mesh geometry={nodes.Cube034.geometry} material={materials['Material.100']} position={[8.15, 9.14, -5.97]} rotation={[0, 0.49, 0]} scale={0.03} />
      <mesh geometry={nodes.Cube035.geometry} material={materials['Material.100']} position={[8.18, 9.14, -5.9]} rotation={[0, 0.49, 0]} scale={0.03} />
      <mesh geometry={nodes.Cube036.geometry} material={materials['Material.100']} position={[8.07, 7.98, -6.11]} rotation={[0, 0.49, 0]} scale={0.03} />
      <mesh geometry={nodes.Cube037.geometry} material={materials['Material.100']} position={[8.11, 7.98, -6.04]} rotation={[0, 0.49, 0]} scale={0.03} />
      <mesh geometry={nodes.Cube038.geometry} material={materials['Material.100']} position={[8.15, 7.98, -5.97]} rotation={[0, 0.49, 0]} scale={0.03} />
      <mesh geometry={nodes.Cube039.geometry} material={materials['Material.100']} position={[8.18, 7.98, -5.9]} rotation={[0, 0.49, 0]} scale={0.03} />
      <mesh geometry={nodes.Cube040.geometry} material={materials['Material.026']} position={[7.07, 6.2, -6.61]} rotation={[0, 0.49, 0]} scale={[0.78, 0.85, 0.85]} />
      <mesh geometry={nodes.Cube041.geometry} material={materials['Material.024']} position={[6.99, 6.2, -6.57]} rotation={[0, 0.49, 0]} scale={[0.78, 0.85, 0.85]} />
      <mesh geometry={nodes.Cube042.geometry} material={materials['Material.059']} position={[7.35, 8.63, -7.13]} rotation={[-Math.PI, 1.08, -Math.PI]} scale={[0.9, -1.11, 0.88]} />
      <mesh geometry={nodes.Cube043.geometry} material={materials['Material.033']} position={[7.35, 8.63, -7.13]} rotation={[-Math.PI, 1.08, -Math.PI]} scale={[0.9, -1.11, 0.88]} />
      <mesh geometry={nodes.Cube044.geometry} material={materials['Material.035']} position={[7.76, 8.45, -6.76]} rotation={[0, 0.49, 0]} scale={0.85} />
      <mesh geometry={nodes.Cube045.geometry} material={materials['Material.105']} position={[7.76, 8.45, -6.76]} rotation={[0, 0.49, 0]} scale={0.85} />
      <mesh geometry={nodes.Cube046.geometry} material={materials['Material.032']} position={[7.35, 8.63, -7.13]} rotation={[-Math.PI, 1.08, -Math.PI]} scale={[0.9, -1.11, 0.88]} />
      <mesh geometry={nodes.Cube049.geometry} material={materials['Material.037']} position={[8.39, 8.7, -3.93]} rotation={[0, 0.49, 0]} scale={[0.52, 0.52, 0.04]} />
      <mesh geometry={nodes.Cube051.geometry} material={materials['Material.037']} position={[8.39, 7.56, -3.93]} rotation={[0, 0.49, 0]} scale={[0.52, 0.52, 0.04]} />
      <mesh geometry={nodes.Cube052.geometry} material={materials['Material.037']} position={[8.39, 6.4, -3.93]} rotation={[0, 0.49, 0]} scale={[0.52, 0.52, 0.04]} />
      <mesh geometry={nodes.Cube053.geometry} material={materials['Material.037']} position={[6.47, 8.75, -6.99]} rotation={[0, 0.49, 0]} scale={[0.52, 0.52, 0.04]} />
      <mesh geometry={nodes.Cube096.geometry} material={materials['Material.037']} position={[7.11, 9.53, -6.03]} rotation={[Math.PI / 2, 0, 1.08]} scale={[0.52, 0.52, 0.04]} />
      <mesh geometry={nodes.Cube097.geometry} material={materials['Material.037']} position={[7.63, 9.53, -5.04]} rotation={[Math.PI / 2, 0, 1.08]} scale={[0.52, 0.52, 0.04]} />
      <mesh geometry={nodes.Cube050.geometry} material={materials['Material.036']} position={[7.51, 7.76, -5.55]} rotation={[0, 0.49, 0]} scale={[0.81, -1.99, 1.87]} />
      <mesh geometry={nodes.Cube054.geometry} material={materials['Material.105']} position={[7.76, 8.45, -6.76]} rotation={[0, 0.49, 0]} scale={0.85} />
      <mesh geometry={nodes.Cube055.geometry} material={materials['Material.063']} position={[7.76, 8.45, -6.76]} rotation={[0, 0.49, 0]} scale={0.85} />
      <mesh geometry={nodes.Cube056.geometry} material={materials['Material.113']} position={[6.66, 7.37, -7.21]} rotation={[0, 0.49, 0]} scale={[0.68, 0.08, 0.85]} />
      <mesh geometry={nodes.Cube057.geometry} material={materials['Material.113']} position={[6.66, 7.53, -7.21]} rotation={[0, 0.49, 0]} scale={[0.68, 0.08, 0.85]} />
      <mesh geometry={nodes.Cube058.geometry} material={materials['Material.113']} position={[6.66, 7.23, -7.21]} rotation={[0, 0.49, 0]} scale={[0.68, 0.08, 0.85]} />
      <mesh geometry={nodes.Cube059.geometry} material={materials['Material.113']} position={[6.66, 7.08, -7.21]} rotation={[0, 0.49, 0]} scale={[0.68, 0.08, 0.85]} />
      <mesh geometry={nodes.Cube060.geometry} material={materials['Material.113']} position={[6.66, 6.91, -7.21]} rotation={[0, 0.49, 0]} scale={[0.68, 0.08, 0.85]} />
      <mesh geometry={nodes.Cube061.geometry} material={materials['Material.049']} position={[8.04, 8.56, -5.82]} rotation={[0, 0.49, 0]} scale={[0.12, 0.54, 0.02]} />
      <mesh geometry={nodes.Cube069.geometry} material={materials['Material.049']} position={[8, 8.56, -5.89]} rotation={[0, 0.49, 0]} scale={[0.12, 0.54, 0.02]} />
      <mesh geometry={nodes.Cube076.geometry} material={materials['Material.049']} position={[7.97, 8.56, -5.96]} rotation={[0, 0.49, 0]} scale={[0.12, 0.54, 0.02]} />
      <mesh geometry={nodes.Cube083.geometry} material={materials['Material.049']} position={[7.93, 8.56, -6.04]} rotation={[0, 0.49, 0]} scale={[0.12, 0.54, 0.02]} />
      <mesh geometry={nodes.Cube062.geometry} material={materials['Material.021']} position={[8.05, 8.56, -5.82]} rotation={[0, 0.49, 0]} scale={[0.1, 0.58, 0.01]} />
      <mesh geometry={nodes.Cube070.geometry} material={materials['Material.021']} position={[8.01, 8.56, -5.89]} rotation={[0, 0.49, 0]} scale={[0.1, 0.58, 0.01]} />
      <mesh geometry={nodes.Cube077.geometry} material={materials['Material.021']} position={[7.97, 8.56, -5.97]} rotation={[0, 0.49, 0]} scale={[0.1, 0.58, 0.01]} />
      <mesh geometry={nodes.Cube084.geometry} material={materials['Material.021']} position={[7.93, 8.56, -6.04]} rotation={[0, 0.49, 0]} scale={[0.1, 0.58, 0.01]} />
      <mesh geometry={nodes.Cube063.geometry} material={materials['Material.038']} position={[5.99, 7.58, -6.86]} rotation={[0, 0.49, -Math.PI / 2]} scale={[0.69, 0.08, 0.85]} />
      <mesh geometry={nodes.Cube064.geometry} material={materials['Material.114']} position={[8.04, 8.56, -5.82]} rotation={[0, 0.49, 0]} scale={[0.12, 0.54, 0.02]} />
      <mesh geometry={nodes.Cube071.geometry} material={materials['Material.114']} position={[8, 8.56, -5.89]} rotation={[0, 0.49, 0]} scale={[0.12, 0.54, 0.02]} />
      <mesh geometry={nodes.Cube078.geometry} material={materials['Material.114']} position={[7.97, 8.56, -5.96]} rotation={[0, 0.49, 0]} scale={[0.12, 0.54, 0.02]} />
      <mesh geometry={nodes.Cube085.geometry} material={materials['Material.114']} position={[7.93, 8.56, -6.04]} rotation={[0, 0.49, 0]} scale={[0.12, 0.54, 0.02]} />
      <mesh geometry={nodes.Cube065.geometry} material={materials['Material.046']} position={[7.98, 8.55, -5.82]} rotation={[0, 0.49, Math.PI]} scale={[0.14, 0.54, 0]} />
      <mesh geometry={nodes.Cube067.geometry} material={materials['Material.046']} position={[8, 8.56, -5.77]} rotation={[-Math.PI, -0.49, -Math.PI]} scale={[0.14, 0.54, 0]} />
      <mesh geometry={nodes.Cube072.geometry} material={materials['Material.046']} position={[7.94, 8.55, -5.89]} rotation={[0, 0.49, Math.PI]} scale={[0.14, 0.54, 0]} />
      <mesh geometry={nodes.Cube074.geometry} material={materials['Material.046']} position={[7.96, 8.56, -5.84]} rotation={[-Math.PI, -0.49, -Math.PI]} scale={[0.14, 0.54, 0]} />
      <mesh geometry={nodes.Cube079.geometry} material={materials['Material.046']} position={[7.9, 8.55, -5.96]} rotation={[0, 0.49, Math.PI]} scale={[0.14, 0.54, 0]} />
      <mesh geometry={nodes.Cube081.geometry} material={materials['Material.046']} position={[7.93, 8.56, -5.91]} rotation={[-Math.PI, -0.49, -Math.PI]} scale={[0.14, 0.54, 0]} />
      <mesh geometry={nodes.Cube086.geometry} material={materials['Material.046']} position={[7.86, 8.55, -6.03]} rotation={[0, 0.49, Math.PI]} scale={[0.14, 0.54, 0]} />
      <mesh geometry={nodes.Cube088.geometry} material={materials['Material.046']} position={[7.89, 8.56, -5.98]} rotation={[-Math.PI, -0.49, -Math.PI]} scale={[0.14, 0.54, 0]} />
      <mesh geometry={nodes.Cube066.geometry} material={materials['Material.048']} position={[7.98, 8.55, -5.82]} rotation={[0, 0.49, Math.PI]} scale={[0.14, 0.54, 0]} />
      <mesh geometry={nodes.Cube068.geometry} material={materials['Material.048']} position={[8, 8.56, -5.77]} rotation={[-Math.PI, -0.49, -Math.PI]} scale={[0.14, 0.54, 0]} />
      <mesh geometry={nodes.Cube073.geometry} material={materials['Material.048']} position={[7.94, 8.55, -5.89]} rotation={[0, 0.49, Math.PI]} scale={[0.14, 0.54, 0]} />
      <mesh geometry={nodes.Cube075.geometry} material={materials['Material.048']} position={[7.96, 8.56, -5.84]} rotation={[-Math.PI, -0.49, -Math.PI]} scale={[0.14, 0.54, 0]} />
      <mesh geometry={nodes.Cube080.geometry} material={materials['Material.048']} position={[7.9, 8.55, -5.96]} rotation={[0, 0.49, Math.PI]} scale={[0.14, 0.54, 0]} />
      <mesh geometry={nodes.Cube082.geometry} material={materials['Material.048']} position={[7.93, 8.56, -5.91]} rotation={[-Math.PI, -0.49, -Math.PI]} scale={[0.14, 0.54, 0]} />
      <mesh geometry={nodes.Cube087.geometry} material={materials['Material.048']} position={[7.86, 8.55, -6.03]} rotation={[0, 0.49, Math.PI]} scale={[0.14, 0.54, 0]} />
      <mesh geometry={nodes.Cube089.geometry} material={materials['Material.048']} position={[7.89, 8.56, -5.98]} rotation={[-Math.PI, -0.49, -Math.PI]} scale={[0.14, 0.54, 0]} />
      <mesh geometry={nodes.Cube091.geometry} material={nodes.Cube091.material} position={[8.51, 9.75, -5.46]} rotation={[0, 0.49, 0]} scale={0.19} />
      <mesh geometry={nodes.Cube094.geometry} material={materials['Material.021']} position={[7.54, 6.74, -6.98]} rotation={[0, 0.49, 0]} scale={[-0.01, -0.01, -0.03]} />
      <mesh geometry={nodes.Cube095.geometry} material={materials['Material.021']} position={[7.54, 9.67, -5.3]} rotation={[0, 0.49, 0]} scale={[0.6, 0.07, 0.6]} />
      <mesh geometry={nodes.Cube098.geometry} material={materials['Material.052']} position={[7.8, 8.53, -6.47]} rotation={[0, 0.49, 0]} scale={[0.01, 0.3, 0.3]} />
      <mesh geometry={nodes.Cube099.geometry} material={materials['Material.055']} position={[6.99, 6.2, -6.57]} rotation={[0, 0.49, 0]} scale={[0.78, 0.85, 0.85]} />
      <mesh geometry={nodes.Cube100.geometry} material={materials['Material.062']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.5, 0.11, 0]} />
      <mesh geometry={nodes.Cube101.geometry} material={materials['Material.064']} position={[7.28, 7.59, -6.46]} rotation={[Math.PI, -0.49, 0]} scale={[0.26, 0, 0.85]} />
      <mesh geometry={nodes.Cube102.geometry} material={materials['Material.066']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.03, 0, 0.04]} />
      <mesh geometry={nodes.Cube103.geometry} material={materials['Material.021']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.41, -0.01, 0.85]} />
      <mesh geometry={nodes.Cube104.geometry} material={materials['Material.021']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.41, -0.01, 0.85]} />
      <mesh geometry={nodes.Cube105.geometry} material={materials['Material.071']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.41, -0.01, 0.85]} />
      <mesh geometry={nodes.Cube106.geometry} material={materials['Material.072']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={-0.14} />
      <mesh geometry={nodes.Cube107.geometry} material={materials['Material.073']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.41, -0.01, 0.85]} />
      <mesh geometry={nodes.Cube108.geometry} material={materials['Material.074']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.41, -0.01, 0.85]} />
      <mesh geometry={nodes.Cube109.geometry} material={materials['Material.075']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.41, -0.01, 0.85]} />
      <mesh geometry={nodes.Cube110.geometry} material={materials['Material.079']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={-0.14} />
      <mesh geometry={nodes.Cube111.geometry} material={materials['Material.080']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.41, -0.01, 0.85]} />
      <mesh geometry={nodes.Cube112.geometry} material={materials['Material.081']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.41, -0.01, 0.85]} />
      <mesh geometry={nodes.Cube113.geometry} material={materials['Material.082']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.08, Math.PI]} scale={[0.01, 0.03, 0.03]} />
      <mesh geometry={nodes.Cube114.geometry} material={materials['Material.083']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.41, -0.01, 0.85]} />
      <mesh geometry={nodes.Cube115.geometry} material={materials['Material.084']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.41, -0.01, 0.85]} />
      <mesh geometry={nodes.Cube116.geometry} material={materials['Material.085']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.05, 0.01, 0.06]} />
      <mesh geometry={nodes.Cube117.geometry} material={materials['Material.066']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.03, 0, 0.04]} />
      <mesh geometry={nodes.Cube118.geometry} material={materials['Material.066']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.03, 0, 0.04]} />
      <mesh geometry={nodes.Cube119.geometry} material={materials['Material.066']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.03, 0, 0.04]} />
      <mesh geometry={nodes.Cube120.geometry} material={materials['Material.066']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.03, 0, 0.04]} />
      <mesh geometry={nodes.Cube121.geometry} material={materials['Material.066']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.03, 0, 0.04]} />
      <mesh geometry={nodes.Cube122.geometry} material={materials['Material.085']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.05, 0.01, 0.06]} />
      <mesh geometry={nodes.Cube123.geometry} material={materials['Material.085']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.05, 0.01, 0.06]} />
      <mesh geometry={nodes.Cube124.geometry} material={materials['Material.085']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.05, 0.01, 0.06]} />
      <mesh geometry={nodes.Cube125.geometry} material={materials['Material.085']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.08, Math.PI]} scale={[0.05, 0.01, 0.06]} />
      <mesh geometry={nodes.Cube126.geometry} material={materials['Material.085']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.08, Math.PI]} scale={[0.05, 0.01, 0.06]} />
      <mesh geometry={nodes.Cube128.geometry} material={materials['Material.067']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.41, -0.01, 0.85]} />
      <mesh geometry={nodes.Cube129.geometry} material={materials['Material.072']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.08, Math.PI]} scale={[0.01, 0.03, 0.03]} />
      <mesh geometry={nodes.Cube130.geometry} material={materials['Material.079']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.41, -0.01, 0.85]} />
      <mesh geometry={nodes.Cube131.geometry} material={materials['Material.072']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.41, -0.01, 0.85]} />
      <mesh geometry={nodes.Cube132.geometry} material={materials['Material.088']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.41, -0.01, 0.85]} />
      <mesh geometry={nodes.Cube133.geometry} material={materials['Material.072']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.41, -0.01, 0.85]} />
      <mesh geometry={nodes.Cube134.geometry} material={materials['Material.072']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.41, -0.01, 0.85]} />
      <mesh geometry={nodes.Cube135.geometry} material={materials['Material.079']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.41, -0.01, 0.85]} />
      <mesh geometry={nodes.Cube136.geometry} material={materials['Material.079']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.41, -0.01, 0.85]} />
      <mesh geometry={nodes.Cube137.geometry} material={materials['Material.079']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.41, -0.01, 0.85]} />
      <mesh geometry={nodes.Cube138.geometry} material={materials['Material.079']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.41, -0.01, 0.85]} />
      <mesh geometry={nodes.Cube139.geometry} material={materials['Material.079']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.41, -0.01, 0.85]} />
      <mesh geometry={nodes.Cube140.geometry} material={materials['Material.079']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.41, -0.01, 0.85]} />
      <mesh geometry={nodes.Cube141.geometry} material={materials['Material.072']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.41, -0.01, 0.85]} />
      <mesh geometry={nodes.Cube142.geometry} material={materials['Material.079']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.41, -0.01, 0.85]} />
      <mesh geometry={nodes.Cube143.geometry} material={materials['Material.079']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.41, -0.01, 0.85]} />
      <mesh geometry={nodes.Cube144.geometry} material={materials['Material.021']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.08, 0.02, 0.02]} />
      <mesh geometry={nodes.Cube145.geometry} material={materials['Material.092']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.08, 0.02, 0.02]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.021']} position={[8.15, 7.73, -5.83]} rotation={[0, 0.49, -Math.PI / 2]} scale={[0.02, 0.01, 0.02]} />
      <mesh geometry={nodes.Cylinder037.geometry} material={materials['Material.021']} position={[7.93, 7.41, -6.25]} rotation={[0, 0.49, -Math.PI / 2]} scale={[0.02, 0.01, 0.02]} />
      <mesh geometry={nodes.Cylinder038.geometry} material={materials['Material.021']} position={[8.17, 7.05, -5.81]} rotation={[0, 0.49, -Math.PI / 2]} scale={[0.02, 0.01, 0.02]} />
      <mesh geometry={nodes.Cylinder107.geometry} material={materials['Material.021']} position={[8.01, 8.22, -6.23]} rotation={[0, 0.49, -Math.PI / 2]} scale={[0.02, 0.01, 0.02]} />
      <mesh geometry={nodes.Cylinder108.geometry} material={materials['Material.021']} position={[8.01, 8.85, -6.23]} rotation={[0, 0.49, -Math.PI / 2]} scale={[0.02, 0.01, 0.02]} />
      <mesh geometry={nodes.Cylinder109.geometry} material={materials['Material.021']} position={[7.71, 8.85, -6.79]} rotation={[0, 0.49, -Math.PI / 2]} scale={[0.02, 0.01, 0.02]} />
      <mesh geometry={nodes.Cylinder110.geometry} material={materials['Material.021']} position={[7.71, 8.22, -6.79]} rotation={[0, 0.49, -Math.PI / 2]} scale={[0.02, 0.01, 0.02]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.109']} position={[7.71, 8.44, -6.76]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.109']} position={[7.68, 8.44, -6.82]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.109']} position={[7.71, 8.5, -6.76]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials['Material.109']} position={[7.68, 8.5, -6.82]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials['Material.109']} position={[7.71, 8.56, -6.76]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials['Material.109']} position={[7.68, 8.56, -6.82]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials['Material.109']} position={[7.71, 8.62, -6.76]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials['Material.109']} position={[7.68, 8.62, -6.82]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder009.geometry} material={materials['Material.109']} position={[7.71, 8.67, -6.76]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder010.geometry} material={materials['Material.109']} position={[7.71, 8.38, -6.76]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder011.geometry} material={materials['Material.109']} position={[7.68, 8.67, -6.82]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder012.geometry} material={materials['Material.109']} position={[7.75, 8.16, -6.68]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder013.geometry} material={materials['Material.109']} position={[7.78, 8.16, -6.63]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder014.geometry} material={materials['Material.109']} position={[7.81, 8.16, -6.57]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder015.geometry} material={materials['Material.109']} position={[7.84, 8.16, -6.52]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder016.geometry} material={materials['Material.109']} position={[7.87, 8.16, -6.47]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder017.geometry} material={materials['Material.109']} position={[7.89, 8.16, -6.41]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder018.geometry} material={materials['Material.109']} position={[7.78, 8.04, -6.63]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder019.geometry} material={materials['Material.109']} position={[7.89, 8.04, -6.41]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder020.geometry} material={materials['Material.109']} position={[8.03, 8.04, -6.16]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder021.geometry} material={materials['Material.109']} position={[8.02, 8.64, -6.17]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder022.geometry} material={materials['Material.109']} position={[8.02, 8.53, -6.17]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder023.geometry} material={materials['Material.109']} position={[8.21, 8.59, -5.81]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder024.geometry} material={materials['Material.109']} position={[8.21, 8.47, -5.81]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder025.geometry} material={materials['Material.109']} position={[8.21, 8.65, -5.81]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder026.geometry} material={materials['Material.109']} position={[8.21, 8.71, -5.81]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder027.geometry} material={materials['Material.109']} position={[8.21, 8.23, -5.81]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder028.geometry} material={materials['Material.109']} position={[8.21, 8.18, -5.81]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder029.geometry} material={materials['Material.109']} position={[8.21, 8.11, -5.81]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder030.geometry} material={materials['Material.109']} position={[8.27, 8.73, -5.7]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder031.geometry} material={materials['Material.109']} position={[8.27, 8.78, -5.7]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder032.geometry} material={materials['Material.109']} position={[7.55, 7.29, -7.07]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder033.geometry} material={materials['Material.109']} position={[7.49, 7.29, -7.18]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder034.geometry} material={materials['Material.109']} position={[7.81, 6.73, -6.57]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder035.geometry} material={materials['Material.109']} position={[7.91, 6.73, -6.39]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder036.geometry} material={materials['Material.109']} position={[8.23, 6.94, -5.77]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder039.geometry} material={materials['Material.109']} position={[7.74, 8.9, -6.7]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder040.geometry} material={materials['Material.109']} position={[7.77, 8.9, -6.65]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder041.geometry} material={materials['Material.109']} position={[7.8, 8.9, -6.59]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder042.geometry} material={materials['Material.109']} position={[7.83, 8.9, -6.54]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder043.geometry} material={materials['Material.109']} position={[7.85, 8.9, -6.49]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder044.geometry} material={materials['Material.109']} position={[7.88, 8.9, -6.43]} rotation={[0, 0.49, -Math.PI / 2]} scale={-0.03} />
      <mesh geometry={nodes.Cylinder045.geometry} material={materials['Material.037']} position={[8.39, 8.7, -3.93]} rotation={[Math.PI / 2, 0, -0.49]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder055.geometry} material={materials['Material.037']} position={[8.39, 7.56, -3.93]} rotation={[Math.PI / 2, 0, -0.49]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder065.geometry} material={materials['Material.037']} position={[8.39, 6.4, -3.93]} rotation={[Math.PI / 2, 0, -0.49]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder075.geometry} material={materials['Material.037']} position={[6.51, 8.76, -6.92]} rotation={[Math.PI / 2, 0, -0.49]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder085.geometry} material={materials['Material.037']} position={[7.11, 9.53, -6.03]} rotation={[-Math.PI, 1.08, 0]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder095.geometry} material={materials['Material.037']} position={[7.63, 9.53, -5.04]} rotation={[-Math.PI, 1.08, 0]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder046.geometry} material={materials['Material.040']} position={[8.39, 8.7, -3.93]} rotation={[Math.PI / 2, 0, -0.49]} scale={[0.45, 0.06, 0.45]} />
      <mesh geometry={nodes.Cylinder056.geometry} material={materials['Material.040']} position={[8.39, 7.56, -3.93]} rotation={[Math.PI / 2, 0, -0.49]} scale={[0.45, 0.06, 0.45]} />
      <mesh geometry={nodes.Cylinder066.geometry} material={materials['Material.040']} position={[8.39, 6.4, -3.93]} rotation={[Math.PI / 2, 0, -0.49]} scale={[0.45, 0.06, 0.45]} />
      <mesh geometry={nodes.Cylinder076.geometry} material={materials['Material.040']} position={[6.51, 8.76, -6.92]} rotation={[Math.PI / 2, 0, -0.49]} scale={[0.45, 0.06, 0.45]} />
      <mesh geometry={nodes.Cylinder047.geometry} material={materials['Material.037']} position={[8.38, 8.7, -3.95]} rotation={[Math.PI / 2, 0, -0.49]} scale={[0.14, 0.15, 0.14]} />
      <mesh geometry={nodes.Cylinder057.geometry} material={materials['Material.037']} position={[8.38, 7.56, -3.95]} rotation={[Math.PI / 2, 0, -0.49]} scale={[0.14, 0.15, 0.14]} />
      <mesh geometry={nodes.Cylinder067.geometry} material={materials['Material.037']} position={[8.38, 6.4, -3.95]} rotation={[Math.PI / 2, 0, -0.49]} scale={[0.14, 0.15, 0.14]} />
      <mesh geometry={nodes.Cylinder077.geometry} material={materials['Material.037']} position={[6.48, 8.75, -6.96]} rotation={[Math.PI / 2, 0, -0.49]} scale={[0.14, 0.15, 0.14]} />
      <mesh geometry={nodes.Cylinder048.geometry} material={materials['Material.037']} position={[8.36, 8.7, -3.99]} rotation={[Math.PI / 2, 0, -0.49]} scale={[0.15, 0.03, 0.15]} />
      <mesh geometry={nodes.Cylinder058.geometry} material={materials['Material.037']} position={[8.36, 7.56, -3.99]} rotation={[Math.PI / 2, 0, -0.49]} scale={[0.15, 0.03, 0.15]} />
      <mesh geometry={nodes.Cylinder068.geometry} material={materials['Material.037']} position={[8.36, 6.4, -3.99]} rotation={[Math.PI / 2, 0, -0.49]} scale={[0.15, 0.03, 0.15]} />
      <mesh geometry={nodes.Cylinder078.geometry} material={materials['Material.037']} position={[6.47, 8.76, -6.98]} rotation={[Math.PI / 2, 0, -0.49]} scale={[0.15, 0.03, 0.15]} />
      <mesh geometry={nodes.Cylinder049.geometry} material={materials['Material.043']} position={[8.36, 8.7, -3.99]} rotation={[Math.PI / 2, 0, -0.49]} scale={[0.15, 0.03, 0.15]} />
      <mesh geometry={nodes.Cylinder059.geometry} material={materials['Material.043']} position={[8.36, 7.56, -3.99]} rotation={[Math.PI / 2, 0, -0.49]} scale={[0.15, 0.03, 0.15]} />
      <mesh geometry={nodes.Cylinder069.geometry} material={materials['Material.043']} position={[8.36, 6.4, -3.99]} rotation={[Math.PI / 2, 0, -0.49]} scale={[0.15, 0.03, 0.15]} />
      <mesh geometry={nodes.Cylinder079.geometry} material={materials['Material.043']} position={[6.47, 8.76, -6.98]} rotation={[Math.PI / 2, 0, -0.49]} scale={[0.15, 0.03, 0.15]} />
      <mesh geometry={nodes.Cylinder050.geometry} material={materials['Material.040']} position={[8.38, 8.7, -3.95]} rotation={[Math.PI / 2, 0, -0.49]} scale={[0.14, 0.15, 0.14]} />
      <mesh geometry={nodes.Cylinder060.geometry} material={materials['Material.040']} position={[8.38, 7.56, -3.95]} rotation={[Math.PI / 2, 0, -0.49]} scale={[0.14, 0.15, 0.14]} />
      <mesh geometry={nodes.Cylinder070.geometry} material={materials['Material.040']} position={[8.38, 6.4, -3.95]} rotation={[Math.PI / 2, 0, -0.49]} scale={[0.14, 0.15, 0.14]} />
      <mesh geometry={nodes.Cylinder080.geometry} material={materials['Material.040']} position={[6.48, 8.75, -6.96]} rotation={[Math.PI / 2, 0, -0.49]} scale={[0.14, 0.15, 0.14]} />
      <mesh geometry={nodes.Cylinder051.geometry} material={materials['Material.037']} position={[8.39, 8.7, -3.93]} rotation={[1.28, -0.49, -0.56]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder061.geometry} material={materials['Material.037']} position={[8.39, 7.56, -3.93]} rotation={[1.28, -0.49, -0.56]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder071.geometry} material={materials['Material.037']} position={[8.39, 6.4, -3.93]} rotation={[1.28, -0.49, -0.56]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder081.geometry} material={materials['Material.037']} position={[6.51, 8.76, -6.92]} rotation={[1.28, -0.49, -0.56]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder091.geometry} material={materials['Material.037']} position={[7.07, 9.53, -6.01]} rotation={[-Math.PI, 0.52, 0]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder101.geometry} material={materials['Material.037']} position={[7.59, 9.53, -5.02]} rotation={[-Math.PI, 0.52, 0]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder052.geometry} material={materials['Material.037']} position={[8.39, 8.75, -3.93]} rotation={[-0.9, -0.86, -2.34]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder062.geometry} material={materials['Material.037']} position={[8.39, 7.61, -3.93]} rotation={[-0.9, -0.86, -2.34]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder072.geometry} material={materials['Material.037']} position={[8.39, 6.45, -3.93]} rotation={[-0.9, -0.86, -2.34]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder082.geometry} material={materials['Material.037']} position={[6.51, 8.8, -6.92]} rotation={[-0.9, -0.86, -2.34]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder053.geometry} material={materials['Material.037']} position={[8.39, 8.7, -3.93]} rotation={[-1.92, 0.57, -2.55]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder054.geometry} material={materials['Material.037']} position={[8.39, 8.7, -3.93]} rotation={[2.29, 0.89, -0.84]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder063.geometry} material={materials['Material.037']} position={[8.39, 7.56, -3.93]} rotation={[-1.92, 0.57, -2.55]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder064.geometry} material={materials['Material.037']} position={[8.39, 7.56, -3.93]} rotation={[2.29, 0.89, -0.84]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder073.geometry} material={materials['Material.037']} position={[8.39, 6.4, -3.93]} rotation={[-1.92, 0.57, -2.55]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder074.geometry} material={materials['Material.037']} position={[8.39, 6.4, -3.93]} rotation={[2.29, 0.89, -0.84]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder083.geometry} material={materials['Material.037']} position={[6.51, 8.76, -6.92]} rotation={[-1.92, 0.57, -2.55]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder084.geometry} material={materials['Material.037']} position={[6.51, 8.76, -6.92]} rotation={[2.29, 0.89, -0.84]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder094.geometry} material={materials['Material.037']} position={[7.07, 9.53, -6.01]} rotation={[0, 0.98, -Math.PI]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder104.geometry} material={materials['Material.037']} position={[7.59, 9.53, -5.02]} rotation={[0, 0.98, -Math.PI]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder086.geometry} material={materials['Material.040']} position={[7.11, 9.53, -6.04]} rotation={[-Math.PI, 1.08, 0]} scale={[0.45, 0.06, 0.45]} />
      <mesh geometry={nodes.Cylinder096.geometry} material={materials['Material.040']} position={[7.63, 9.53, -5.05]} rotation={[-Math.PI, 1.08, 0]} scale={[0.45, 0.06, 0.45]} />
      <mesh geometry={nodes.Cylinder087.geometry} material={materials['Material.037']} position={[7.11, 9.56, -6.03]} rotation={[-Math.PI, 1.08, 0]} scale={[0.14, 0.15, 0.14]} />
      <mesh geometry={nodes.Cylinder097.geometry} material={materials['Material.037']} position={[7.63, 9.56, -5.05]} rotation={[-Math.PI, 1.08, 0]} scale={[0.14, 0.15, 0.14]} />
      <mesh geometry={nodes.Cylinder088.geometry} material={materials['Material.037']} position={[7.11, 9.58, -6.03]} rotation={[-Math.PI, 1.08, 0]} scale={[0.15, 0.03, 0.15]} />
      <mesh geometry={nodes.Cylinder098.geometry} material={materials['Material.037']} position={[7.63, 9.58, -5.05]} rotation={[-Math.PI, 1.08, 0]} scale={[0.15, 0.03, 0.15]} />
      <mesh geometry={nodes.Cylinder089.geometry} material={materials['Material.043']} position={[7.11, 9.58, -6.03]} rotation={[-Math.PI, 1.08, 0]} scale={[0.15, 0.03, 0.15]} />
      <mesh geometry={nodes.Cylinder099.geometry} material={materials['Material.043']} position={[7.63, 9.58, -5.05]} rotation={[-Math.PI, 1.08, 0]} scale={[0.15, 0.03, 0.15]} />
      <mesh geometry={nodes.Cylinder090.geometry} material={materials['Material.040']} position={[7.11, 9.56, -6.03]} rotation={[-Math.PI, 1.08, 0]} scale={[0.14, 0.15, 0.14]} />
      <mesh geometry={nodes.Cylinder100.geometry} material={materials['Material.040']} position={[7.63, 9.56, -5.05]} rotation={[-Math.PI, 1.08, 0]} scale={[0.14, 0.15, 0.14]} />
      <mesh geometry={nodes.Cylinder092.geometry} material={materials['Material.037']} position={[7.08, 9.54, -5.99]} rotation={[-Math.PI, -1.02, 0]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder102.geometry} material={materials['Material.037']} position={[7.6, 9.54, -5.01]} rotation={[-Math.PI, -1.02, 0]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder093.geometry} material={materials['Material.037']} position={[7.07, 9.53, -6.01]} rotation={[0, -0.42, Math.PI]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder103.geometry} material={materials['Material.037']} position={[7.59, 9.53, -5.02]} rotation={[0, -0.42, Math.PI]} scale={[0.5, 0.09, 0.5]} />
      <mesh geometry={nodes.Cylinder105.geometry} material={materials['Material.053']} position={[7.82, 8.54, -6.47]} rotation={[0, 0.49, -Math.PI / 2]} scale={0.27} />
      <mesh geometry={nodes.Cylinder106.geometry} material={materials['Material.054']} position={[7.82, 8.54, -6.47]} rotation={[0, 0.49, -Math.PI / 2]} scale={0.27} />
      <mesh geometry={nodes.Cylinder111.geometry} material={materials['Material.096']} position={[7.08, 7.6, -6.87]} rotation={[0, 0.49, 0]} scale={0.11} />
      <mesh geometry={nodes.Cylinder113.geometry} material={materials['Material.096']} position={[7.46, 7.6, -6.15]} rotation={[0, 0.49, 0]} scale={0.11} />
      <mesh geometry={nodes.Cylinder112.geometry} material={materials['Material.095']} position={[7.08, 7.6, -6.87]} rotation={[0, 0.49, 0]} scale={0.11} />
      <mesh geometry={nodes.Cylinder114.geometry} material={materials['Material.095']} position={[7.46, 7.6, -6.15]} rotation={[0, 0.49, 0]} scale={0.11} />
      <mesh geometry={nodes.Cylinder115.geometry} material={materials['Material.021']} position={[7.91, 8.66, -6.17]} rotation={[0, 0.49, -Math.PI / 2]} scale={0.04} />
      <mesh geometry={nodes.Cylinder116.geometry} material={materials['Material.021']} position={[7.91, 8.46, -6.17]} rotation={[0, 0.49, -Math.PI / 2]} scale={0.04} />
      <mesh geometry={nodes.Cylinder117.geometry} material={materials['Material.021']} position={[8.63, 9.76, -5.1]} rotation={[0, 0.49, 0]} scale={0.03} />
      <mesh geometry={nodes.Cylinder118.geometry} material={materials['Material.058']} position={[8.72, 9.76, -5.14]} rotation={[0, 0.49, 0]} scale={0.03} />
      <mesh geometry={nodes.Cylinder120.geometry} material={materials['Material.061']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={0.35} />
      <mesh geometry={nodes.Cylinder121.geometry} material={materials['Material.068']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[-0.04, 0, -0.04]} />
      <mesh geometry={nodes.Cylinder122.geometry} material={materials['Material.068']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[-0.04, 0, -0.04]} />
      <mesh geometry={nodes.Cylinder123.geometry} material={materials['Material.068']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[-0.04, 0, -0.04]} />
      <mesh geometry={nodes.Cylinder124.geometry} material={materials['Material.068']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[-0.04, 0, -0.04]} />
      <mesh geometry={nodes.Cylinder125.geometry} material={materials['Material.068']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[-0.04, 0, -0.04]} />
      <mesh geometry={nodes.Cylinder126.geometry} material={materials['Material.068']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[-0.04, 0, -0.04]} />
      <mesh geometry={nodes.Cylinder127.geometry} material={materials['Material.076']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder128.geometry} material={materials['Material.077']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder129.geometry} material={materials['Material.078']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder130.geometry} material={materials['Material.076']} position={[7.28, 7.59, -6.46]} rotation={[Math.PI, 0.73, 0]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder131.geometry} material={materials['Material.077']} position={[7.28, 7.59, -6.46]} rotation={[Math.PI, 0.73, 0]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder132.geometry} material={materials['Material.078']} position={[7.28, 7.59, -6.46]} rotation={[Math.PI, 0.73, 0]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder133.geometry} material={materials['Material.076']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.15, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder134.geometry} material={materials['Material.077']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.15, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder135.geometry} material={materials['Material.078']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.15, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder136.geometry} material={materials['Material.076']} position={[7.28, 7.59, -6.46]} rotation={[0, -0.96, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder137.geometry} material={materials['Material.077']} position={[7.28, 7.59, -6.46]} rotation={[0, -0.96, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder138.geometry} material={materials['Material.078']} position={[7.28, 7.59, -6.46]} rotation={[0, -0.96, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder139.geometry} material={materials['Material.076']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.57, 3.14]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder140.geometry} material={materials['Material.077']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.57, 3.14]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder141.geometry} material={materials['Material.078']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.57, 3.14]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder142.geometry} material={materials['Material.076']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.08, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder143.geometry} material={materials['Material.077']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.08, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder144.geometry} material={materials['Material.078']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.08, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder145.geometry} material={materials['Material.076']} position={[7.28, 7.59, -6.46]} rotation={[0, -0.58, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder146.geometry} material={materials['Material.077']} position={[7.28, 7.59, -6.46]} rotation={[0, -0.58, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder147.geometry} material={materials['Material.078']} position={[7.28, 7.59, -6.46]} rotation={[0, -0.58, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder148.geometry} material={materials['Material.076']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.4, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder149.geometry} material={materials['Material.077']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.4, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder150.geometry} material={materials['Material.078']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.4, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder151.geometry} material={materials['Material.076']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.41, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder152.geometry} material={materials['Material.077']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.41, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder153.geometry} material={materials['Material.078']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.41, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder154.geometry} material={materials['Material.076']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.41, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder155.geometry} material={materials['Material.077']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.41, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder156.geometry} material={materials['Material.078']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.41, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder157.geometry} material={materials['Material.076']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.41, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder158.geometry} material={materials['Material.077']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.41, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder159.geometry} material={materials['Material.078']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.41, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder160.geometry} material={materials['Material.076']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.41, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder161.geometry} material={materials['Material.077']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.41, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder162.geometry} material={materials['Material.078']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.41, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder163.geometry} material={materials['Material.076']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.41, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder164.geometry} material={materials['Material.077']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.41, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder165.geometry} material={materials['Material.078']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.41, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder166.geometry} material={materials['Material.076']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.41, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder167.geometry} material={materials['Material.077']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.41, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder168.geometry} material={materials['Material.078']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.41, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder169.geometry} material={materials['Material.076']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.41, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder170.geometry} material={materials['Material.077']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.41, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder171.geometry} material={materials['Material.078']} position={[7.28, 7.59, -6.46]} rotation={[0, -1.41, Math.PI]} scale={[0.03, 0.02, 0.03]} />
      <mesh geometry={nodes.Cylinder172.geometry} material={materials['Material.068']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, 0]} scale={[-0.03, 0, -0.03]} />
      <mesh geometry={nodes.Cylinder173.geometry} material={materials['Material.068']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, 0]} scale={[-0.03, 0, -0.03]} />
      <mesh geometry={nodes.Cylinder185.geometry} material={materials['Material.091']} position={[7.28, 7.59, -6.46]} rotation={[-Math.PI / 2, 0, -2.65]} scale={0.01} />
      <mesh geometry={nodes.Cylinder186.geometry} material={materials['Material.091']} position={[7.28, 7.59, -6.46]} rotation={[-Math.PI / 2, 0, -2.65]} scale={0.01} />
      <mesh geometry={nodes.GamerStorm_logo.geometry} material={materials.GamerStorm_logo} position={[8.36, 9.77, -4.04]} rotation={[0, 0.49, 0]} scale={0.21} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.111']} position={[8.09, 7.39, -6.06]} rotation={[0, 0.49, -Math.PI / 2]} scale={0.16} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['Material.113']} position={[6.41, 8.74, -7.06]} rotation={[Math.PI / 2, 0, -0.49]} scale={0.82} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['Material.021']} position={[7.32, 9.76, -5.75]} rotation={[0, 0.49, 0]} scale={[0.71, 0.85, 1.28]} />
      <mesh geometry={nodes.Plane004.geometry} material={materials['Material.021']} position={[7.32, 9.77, -5.77]} rotation={[0, 0.49, 0]} scale={[0.7, 0.85, 1.29]} />
      <mesh geometry={nodes.Plane075.geometry} material={materials['Material.004']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.09, 0.09, 0.03]} />
      <mesh geometry={nodes.Plane076.geometry} material={materials['Material.086']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.09, 0.09, 0.03]} />
      <mesh geometry={nodes.ROGTRANSPARENT.geometry} material={materials.ROGTRANSPARENT} position={[8.07, 7.36, -5.98]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.35} />
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.068']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.03, 0.01, 0.03]} />
      <mesh geometry={nodes.Sphere001.geometry} material={materials['Material.068']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.03, 0.01, 0.03]} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials['Material.068']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.03, 0.01, 0.03]} />
      <mesh geometry={nodes.Sphere003.geometry} material={materials['Material.068']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.03, 0.01, 0.03]} />
      <mesh geometry={nodes.Sphere004.geometry} material={materials['Material.068']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.03, 0.01, 0.03]} />
      <mesh geometry={nodes.Sphere005.geometry} material={materials['Material.068']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, Math.PI]} scale={[0.03, 0.01, 0.03]} />
      <mesh geometry={nodes.Sphere006.geometry} material={materials['Material.068']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, 0]} scale={[0.02, 0.01, 0.02]} />
      <mesh geometry={nodes.Sphere007.geometry} material={materials['Material.068']} position={[7.28, 7.59, -6.46]} rotation={[0, 0.49, 0]} scale={[0.02, 0.01, 0.02]} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.021']} position={[7.68, 8.38, -6.75]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text001.geometry} material={materials['Material.021']} position={[7.68, 8.44, -6.75]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text002.geometry} material={materials['Material.021']} position={[7.65, 8.44, -6.81]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text003.geometry} material={materials['Material.021']} position={[7.68, 8.5, -6.75]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text004.geometry} material={materials['Material.021']} position={[7.65, 8.5, -6.81]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text005.geometry} material={materials['Material.021']} position={[7.68, 8.56, -6.75]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text006.geometry} material={materials['Material.021']} position={[7.65, 8.56, -6.81]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text007.geometry} material={materials['Material.021']} position={[7.68, 8.62, -6.75]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text008.geometry} material={materials['Material.021']} position={[7.65, 8.62, -6.81]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text009.geometry} material={materials['Material.021']} position={[7.68, 8.68, -6.75]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text010.geometry} material={materials['Material.021']} position={[7.65, 8.68, -6.81]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text011.geometry} material={materials['Material.021']} position={[7.73, 8.17, -6.67]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text012.geometry} material={materials['Material.021']} position={[7.75, 8.17, -6.62]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text013.geometry} material={materials['Material.021']} position={[7.78, 8.17, -6.57]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text014.geometry} material={materials['Material.021']} position={[7.81, 8.17, -6.52]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text015.geometry} material={materials['Material.021']} position={[7.84, 8.17, -6.46]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text016.geometry} material={materials['Material.021']} position={[7.86, 8.17, -6.41]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text017.geometry} material={materials['Material.021']} position={[7.75, 8.05, -6.62]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text018.geometry} material={materials['Material.021']} position={[7.87, 8.05, -6.41]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text019.geometry} material={materials['Material.021']} position={[8, 8.05, -6.16]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text020.geometry} material={materials['Material.021']} position={[7.99, 8.64, -6.16]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text021.geometry} material={materials['Material.021']} position={[7.99, 8.54, -6.16]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text022.geometry} material={materials['Material.021']} position={[8.18, 8.6, -5.81]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text023.geometry} material={materials['Material.021']} position={[8.18, 8.47, -5.81]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text024.geometry} material={materials['Material.021']} position={[8.18, 8.66, -5.81]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text025.geometry} material={materials['Material.021']} position={[8.18, 8.72, -5.81]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text026.geometry} material={materials['Material.021']} position={[8.18, 8.24, -5.81]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text027.geometry} material={materials['Material.021']} position={[8.18, 8.18, -5.81]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text028.geometry} material={materials['Material.021']} position={[8.18, 8.12, -5.81]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text029.geometry} material={materials['Material.021']} position={[8.24, 8.73, -5.7]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text030.geometry} material={materials['Material.021']} position={[8.24, 8.79, -5.7]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text031.geometry} material={materials['Material.021']} position={[7.52, 7.29, -7.06]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text032.geometry} material={materials['Material.021']} position={[7.46, 7.29, -7.17]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text033.geometry} material={materials['Material.021']} position={[7.78, 6.73, -6.56]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text034.geometry} material={materials['Material.021']} position={[7.88, 6.73, -6.38]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text035.geometry} material={materials['Material.021']} position={[8.2, 6.94, -5.77]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text036.geometry} material={materials['Material.021']} position={[7.71, 8.91, -6.69]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text037.geometry} material={materials['Material.021']} position={[7.74, 8.91, -6.64]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text038.geometry} material={materials['Material.021']} position={[7.77, 8.91, -6.59]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text039.geometry} material={materials['Material.021']} position={[7.8, 8.91, -6.54]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text040.geometry} material={materials['Material.021']} position={[7.83, 8.91, -6.48]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text041.geometry} material={materials['Material.021']} position={[7.85, 8.91, -6.43]} rotation={[Math.PI / 2, 0, 1.08]} scale={0.01} />
      <mesh geometry={nodes.Text042.geometry} material={materials['Material.118']} position={[6.66, 7.52, -6.8]} rotation={[Math.PI / 2, 0, 1.08]} scale={[0.8, 0.04, 0.57]} />
      <mesh geometry={nodes.Text043.geometry} material={materials['Material.045']} position={[7.93, 9.05, -5.79]} rotation={[-Math.PI, 1.08, Math.PI / 2]} scale={0.05} />
      <mesh geometry={nodes.Text044.geometry} material={materials['Material.045']} position={[7.95, 8.07, -5.75]} rotation={[-Math.PI, 1.08, -Math.PI / 2]} scale={0.05} />
      <mesh geometry={nodes.Text045.geometry} material={materials['Material.045']} position={[7.89, 8.61, -5.75]} rotation={[Math.PI, -0.49, Math.PI / 2]} scale={0.03} />
      <mesh geometry={nodes.Text046.geometry} material={materials['Material.045']} position={[7.89, 9.05, -5.86]} rotation={[-Math.PI, 1.08, Math.PI / 2]} scale={0.05} />
      <mesh geometry={nodes.Text047.geometry} material={materials['Material.045']} position={[7.91, 8.07, -5.82]} rotation={[-Math.PI, 1.08, -Math.PI / 2]} scale={0.05} />
      <mesh geometry={nodes.Text048.geometry} material={materials['Material.045']} position={[7.85, 8.61, -5.82]} rotation={[Math.PI, -0.49, Math.PI / 2]} scale={0.03} />
      <mesh geometry={nodes.Text049.geometry} material={materials['Material.045']} position={[7.86, 9.05, -5.93]} rotation={[-Math.PI, 1.08, Math.PI / 2]} scale={0.05} />
      <mesh geometry={nodes.Text050.geometry} material={materials['Material.045']} position={[7.88, 8.07, -5.89]} rotation={[-Math.PI, 1.08, -Math.PI / 2]} scale={0.05} />
      <mesh geometry={nodes.Text051.geometry} material={materials['Material.045']} position={[7.81, 8.61, -5.89]} rotation={[Math.PI, -0.49, Math.PI / 2]} scale={0.03} />
      <mesh geometry={nodes.Text052.geometry} material={materials['Material.045']} position={[7.82, 9.05, -6]} rotation={[-Math.PI, 1.08, Math.PI / 2]} scale={0.05} />
      <mesh geometry={nodes.Text053.geometry} material={materials['Material.045']} position={[7.84, 8.07, -5.96]} rotation={[-Math.PI, 1.08, -Math.PI / 2]} scale={0.05} />
      <mesh geometry={nodes.Text054.geometry} material={materials['Material.045']} position={[7.78, 8.61, -5.97]} rotation={[Math.PI, -0.49, Math.PI / 2]} scale={0.03} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Blue paint old']} position={[6.28, 8.42, -8.37]} scale={[1, 1.76, 1]} />
      <mesh geometry={nodes.Plane005.geometry} material={materials['Material.004']} position={[6.13, 0, 0]} scale={32.49} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Losck screen']} position={[1.65, 7.45, -6.78]} rotation={[0, -0.22, 0]} />
      <group position={[-4.4, 7.45, -6.76]} rotation={[0, 0.23, 0]}>
        <mesh geometry={nodes.Cube152_1.geometry} material={materials['Color 1']} />
        <mesh geometry={nodes.Cube152_2.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Cube152_3.geometry} material={materials.Dark} />
        <mesh geometry={nodes.Cube152_4.geometry} material={materials.Blue} />
        <mesh geometry={nodes.Cube152_5.geometry} material={materials['Color 2']} />
        <mesh geometry={nodes.Cube152_6.geometry} material={materials['Color 3']} />
      </group>
      <group position={[1.65, 7.45, -6.81]} rotation={[0, -0.22, 0]}>
        <mesh geometry={nodes.Cube152_1.geometry} material={materials['Color 1']} />
        <mesh geometry={nodes.Cube152_2.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Cube152_3.geometry} material={materials.Dark} />
        <mesh geometry={nodes.Cube152_4.geometry} material={materials.Blue} />
        <mesh geometry={nodes.Cube152_5.geometry} material={materials['Color 2']} />
        <mesh geometry={nodes.Cube152_6.geometry} material={materials['Color 3']} />
      </group>
    </group>
  )
}

useGLTF.preload('models/Desk-transformed.glb')
