export const posts = [
  {
    slug: 'astra-the-good-and-the-bad',
    title: 'Astra: the good and the bad',
    excerpt: 'A candid note on what is exciting about Astra, the tradeoffs worth naming, and how we will keep learning from the rollout.',
    date: 'September 7, 2026',
    readTime: '6 min read',
    tags: ['Product', 'Lessons learned'],
    body: [
      { heading: 'The problem Astra is trying to solve', paragraphs: ['Astra begins with a simple constraint: people should not need to learn a new system just to complete an important task. The experience should make the next useful step obvious, preserve context, and make outcomes feel dependable rather than surprising.', 'That is deliberately narrower than trying to be everything to everyone. A clear core loop gives the product a reason to exist, gives users a reason to return, and gives the team an honest way to decide what not to build yet.'] },
      { heading: 'What is working', paragraphs: ['The strongest part of Astra is focus. A smaller, more opinionated surface makes the product easier to understand and gives the team room to polish the moments that create trust: first use, the primary task, and recovery when something does not go as expected.', 'The rollout is also staged by design. Each release is an opportunity to observe actual behavior before expanding the audience. That creates a feedback loop around activation, task completion, repeat use, support signals, and reliability—not just a one-way feature delivery process.'], diagram: 'astra' },
      { heading: 'The hard parts we should name', paragraphs: ['Focus creates gaps. Some useful workflows will not be covered on day one, and early users will encounter edges that feel unfinished. Those are real tradeoffs, not details to hide behind launch language.', 'There is also a persistent tension between speed and confidence. Moving quickly is valuable only when the system remains understandable, observable, and safe to change. Privacy, reliability, and coherent product behavior must be part of the foundation; they cannot be deferred until after people depend on the product.'] },
      { heading: 'How the architecture supports the rollout', paragraphs: ['Astra is organized as clear, independent layers. The experience layer keeps the interface focused. The workflow layer turns user intent into explicit actions. Shared services handle identity, data access, integrations, and notifications. The operations layer makes the system measurable and gives the team controls to operate it responsibly.', 'The point is not architectural complexity for its own sake. Clear boundaries let the team improve a single capability without destabilizing the rest of the product, and they make failures easier to understand. The architecture protects the pace of learning.'], diagram: 'astra-architecture', callout: 'Design principle: keep the user experience simple while making the system underneath observable, secure, and easy to change.' },
      { heading: 'Goals and plans', paragraphs: ['Near term, the goal is to prove a strong core loop: make first use clear, help people complete the primary task, and remove the friction that prevents a return visit. Success should be reflected in activation, repeat use, qualitative feedback, and reliability—not vanity metrics alone.', 'From there, the plan is to deepen the workflows people already rely on, strengthen the integrations around them, and expand only when the foundation is ready. Astra should grow because users are pulling it forward, not because a feature list says it has to.'] }
    ]
  },
  {
    slug: 'goloadout-architecture-goals-and-plans',
    title: 'goLoadout: architecture, goals, and plans',
    excerpt: 'How goLoadout is being shaped around a portable tactical gaming identity—and the system designed to let it grow with the community.',
    date: 'September 7, 2026',
    readTime: '7 min read',
    tags: ['goLoadout', 'Architecture', 'Roadmap'],
    body: [
      { heading: 'A tactical identity that travels', paragraphs: ['goLoadout is built on the belief that a tactical gaming identity should not stop at the screen. The goal is to give players a home for the gear, style, and connections that make their identity feel personal—online and in the field.', 'The product should make that identity easy to express, easy to carry, and useful to the communities that form around shared play. The identity belongs to the player; the platform’s role is to make it useful.'] },
      { heading: 'The core product loop', paragraphs: ['The first version focuses on a simple loop: establish an identity, create a loadout, and share it where it creates connection. Each step should create value on its own, while making the next step more compelling.', 'This is important because social products need a useful individual experience before they can become valuable as a network. A player should be proud of a profile and find a loadout useful even before a friend sees it.'], diagram: 'goloadout-loop' },
      { heading: 'Architecture that can evolve', paragraphs: ['goLoadout is designed in clear layers. The experience layer provides a fast, visual player-facing interface. The domain layer owns profiles, loadouts, and the rules that connect them. A sharing layer makes that identity portable across community touchpoints. Supporting services establish the boundaries around permissions, data, and integrations.', 'Keeping these concerns separate gives the product room to improve individual capabilities without destabilizing the whole system. It also creates the conditions for a responsible platform: the team can understand what happens at the boundaries, protect player data, and make changes without losing sight of the social experience.'], diagram: 'goloadout-architecture', callout: 'Design principle: give players a portable identity, while keeping the rules, permissions, and connections explicit.' },
      { heading: 'Roadmap: deepen before expanding', paragraphs: ['The immediate plan is a strong core: a compelling identity, useful loadouts, and a simple path to share them. The next phase can deepen the community features and real-world connections that make goLoadout distinct.', 'The roadmap should be guided by the people already choosing to bring it with them. The best next feature is not the loudest one; it is the one that makes the existing player experience more valuable and gives the community another reason to return.'] }
    ]
  }
];
